AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2  # one for cocksidiosis images and the other for healthy images
WEIGHTS: imagenet
LEARNING_RATE: 0.01